
name: CI main

on:
  push:
    branches: [ "master", "main", "devel" ]
  pull_request:
    branches: [ "master", "main", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 && python3 -m pip install pip -U
    - name: Run build
      run: pip3 install --user .
    - name: Run build all
      run: pip3 install --user .[dev,test]
    - name: Run tests and collect coverage
      run: pytest -v --cov=./src
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Type check
      run: mypy
    - name: Linter check
      run: pylint ./src/ ./tests/
